config/routes.rb
Rails.application.routes.draw do
  get 'students/index'

  devise_for :users

  resources :students

  get 'feed/:id', to: 'students#feed', as: :feed
  get 'sleep/:id', to: 'students#sleep', as: :sleep
  get 'bath/:id', to: 'students#bath', as: :bath
  get 'exercise/:id', to: 'students#exercise', as: :exercise
  get 'cure/:id', to: 'students#cure', as: :cure
  get 'study/:id', to: 'students#study', as: :study
  put 'convert_points/:id', to: 'students#convert_points', as: :convert_points

  get 'update/:id', to: 'students#update', as: :update

  get 'ranking', to: 'students#ranking', as: :ranking

  get 'play/:id', to: 'students#play', as: :play

  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user
	after_initialize :set_defaults, if: 'new_record?'

	private
	def set_defaults
		self.mood = 100
		self.hunger = 100
		self.health = 100
		self.energy = 100
		self.hygiene = 100
		self.coefficient = 0.0
		self.icon = "happy"
		self.last_page_refresh = Time.now()
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :students, dependent: :destroy        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!
	skip_before_action :verify_authenticity_token

	def index
  		@students = current_user.students
	end

	def new
		@student = Student.new
	end

	def create
		@student = current_user.students.build(student_params)
 
  		if @student.save
  			redirect_to @student
  		else
  			render 'new'
  		end
	end

	def show
		@student = Student.find(params[:id])

		if @student.icon != "dead"
			tick(@student)
		end
	end

	def destroy
  		@student = Student.find(params[:id])
  		@student.destroy
 
  		redirect_to students_path
	end

	def ranking
		@students = Student.order(:coefficient)
	end

	def update
		@student = Student.find(params[:id])

		if @student.icon != "dead"
			tick(@student)
		end

		respond_to do |format|
      		format.html
      		format.json { render json: @student }
      	end
	end

	def feed
		@student = Student.find(params[:id])

		if @student.icon != "dead"

			@student.hunger += 4
			@student.health -= 1
			@student.mood += 2
			@student.updated_at = Time.now

			if @student.hunger > 100
				@student.hunger = 100
				@student.health = 50
			end
			if @student.health > 100
				@student.health = 100
			end	
			if @student.mood > 100
				@student.mood = 100
			end

			@student.save
		end
	
		respond_to do |format|
    		format.html
    		format.json { render json: @student }
    	end
	end

	def cure
		@student = Student.find(params[:id])

		if @student.icon != "dead"
			@student.energy += 2
			@student.health += 20
			@student.mood += 3

			if @student.energy > 100
				@student.energy = 100
			end
			if @student.health > 100
				@student.health = 20
			end
			if @student.mood > 100
				@student.mood = 100
			end

			@student.updated_at = Time.now

			@student.save
		end

		respond_to do |format|
      		format.html
      		format.json { render json: @student }
      	end
	end

	def play
		@student = Student.find(params[:id])
	end

	def convert_points
		@student = Student.find(params[:id])
		@student.mood += params[:mood].to_i
		@student.energy -= params[:energy].to_i

		if @student.mood > 100
			@student.mood = 100
		end
		if @student.energy < 0
			@student.energy = 0
		end

		@student.updated_at = Time.now
		@student.save

		redirect_to student_path(@student)
	end

	def sleep
		@student = Student.find(params[:id])

		if @student.icon != "dead"

			@student.energy += 50
			@student.health += 1
			@student.mood += 2

			if @student.energy > 100
				@student.energy = 100
			end
			if @student.health > 100
				@student.health = 100
			end
			if @student.mood > 100
				@student.mood = 100
			end

			@student.updated_at = Time.now

			@student.save
		end

		respond_to do |format|
      		format.html
      		format.json { render json: @student }
      	end

	end

	def exercise
		@student = Student.find(params[:id])

		if @student.icon != "dead"

			@student.energy -= 20
			@student.health += 20
			@student.mood += 2

			if @student.health > 100
				@student.health = 100
			end
			if @student.mood > 100
				@student.mood = 100
			end

			@student.updated_at = Time.now

			@student.save
		end

		respond_to do |format|
      		format.html
      		format.json { render json: @student }
      	end

	end

	def bath
		@student = Student.find(params[:id])

		if @student.icon != "dead"

			@student.energy += 1
			@student.hygiene += 40
			@student.health += 2
			@student.mood += 2

			if @student.energy > 100
				@student.energy = 100
			end
			if @student.health > 100
				@student.health = 100
			end
			if @student.mood > 100
				@student.mood = 100
			end
			if @student.hygiene > 100
				@student.hygiene = 100
			end

			@student.updated_at = Time.now

			@student.save
		end

		respond_to do |format|
      		format.html
      		format.json { render json: @student }
      	end
	end

	def study
		@student = Student.find(params[:id])

		if @student.icon != "dead"

			@student.energy -= 35
			@student.hygiene -= 10
			@student.health -= 10
			@student.mood -= 20
			@student.coefficient += 0.05

			if @student.energy > 100
				@student.energy = 100
			end
			if @student.health > 100
				@student.health = 100
			end
			if @student.mood > 100
				@student.mood = 100
			end
			if @student.hygiene > 100
				@student.hygiene = 100
			end
			if @student.coefficient > 1.0
				@student.coefficient = 1.0
			end

			@student.updated_at = Time.now

			@student.save
		end

		respond_to do |format|
      		format.html
      		format.json { render json: @student }
      	end
	end

	def tick(student)
		hungerRate = 0
		hygieneRate = 0
		energyRate = 0
		moodRate = 0
		healthRate = 0

		if student.mood <= 0 or student.health <= 0
			student.icon = "dead"
			student.mood = 0
			student.health = 0
			student.hygiene = 0
			student.hunger = 0
			student.energy = 0
		elsif student.health <= 50 and student.health > 0
			hungerRate = 10
			hygieneRate = 10
			energyRate = 10
			moodRate = 20
			healthRate = 10
			student.icon = "sick"
		elsif student.health <= 25 and student.health > 0
			hungerRate = 20
			hygieneRate = 20
			energyRate = 20
			moodRate = 30
			healthRate = 20
			student.icon = "sick"
		elsif student.mood > 75
			hungerRate = 2
			hygieneRate = 2
			energyRate = 2
			moodRate = 2
			healthRate = 2
			student.icon = "happy"
		elsif student.mood <= 75 and student.mood > 50
			hungerRate = 3
			hygieneRate = 3
			energyRate = 3
			moodRate = 3
			healthRate = 3
			student.icon = "shy"
		elsif student.mood <= 50 and student.mood > 25
			hungerRate = 4
			hygieneRate = 4
			energyRate = 4
			moodRate = 4
			healthRate = 4
			student.icon = "sad"
		elsif student.mood <= 25
			hungerRate = 5
			hygieneRate = 5
			energyRate = 5
			moodRate = 5
			healthRate = 5
			student.icon = "cry"
		end

		delta = Time.now - student.last_page_refresh

		if delta > 5

			while delta > 5 do


				student.mood -= moodRate * Random.rand(0.5..2.0)
				student.hunger -= hungerRate * Random.rand(0.5..1.5)
				student.health -= healthRate * Random.rand(0.5..3)
				student.hygiene -= hygieneRate * Random.rand(0.5..3)
				student.energy -= energyRate * Random.rand(0.5..1.5)

				delta -= 5
			end

			student.last_page_refresh = Time.now

			student.save
		end
	end

	private
  		def student_params
    		params.require(:student).permit(:name, :age, :gender, :bachelor_degree, :coefficient, :cash, :mood, :hunger, :health, :energy, :last_active)
  		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calouro Simulator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tabela de Rancking</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body style="background: #e9faff;">
    <section>
        <div class="row" style="margin: 0">
            <div class="col-xl-2" style="padding: 0;"></div>
            <div class="col-xl-8" style="padding: 0; margin-top: 10px;">
                <div class="row" style="margin: 0">
                    <table class="table">
                        <thead>
                            <tr class="table-secondary">
                                <th class="text-center">Nome do Pet</th>
                                <th class="text-center">Idade</th>
                                <th class="text-center">Sexo</th>
                                <th class="text-center">Curso</th>
                                <th class="text-center">Coeficiente</th>
                                <th class="text-center">Mostrar</th>
                                <th class="text-center">Excluir</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <% @students.each do |student| %>
                                    <tr>
                                        <td class="text-center"><%= student.name %></td>
                                        <td class="text-center"><%= student.age %></td>
                                        <td class="text-center"><%= student.gender %></td>
                                        <td class="text-center"><%= student.bachelor_degree %></td>
                                        <td class="text-center"><%= student.coefficient %></td>
                                        <td class="text-center">
                                            <%= link_to student_path(student), :method => :get do %>
                                                <button type="button" class="btn btn-primary float-right" style="margin-right: 10px; margin-top: 10px;">Mostrar</button>
                                            <% end %>
                                        </td>
                                        <td class="text-center">
                                            <%= link_to student_path(student), method: :delete do %>
                                                <button type="button" class="btn btn-primary float-right" style="margin-right: 10px; margin-top: 10px;">Excluir</button>
                                            <% end %>
                                        </td>
                                     </tr>
                                <% end %>
                        </tbody>
                    </table>
                </div>

                <%= link_to destroy_user_session_path, method: :delete do %>
                    <button type="button" class="btn btn-primary float-right" style="margin-right: 10px; margin-top: 10px;">Sair</button>
                <% end %>

                <%= link_to new_student_path do %>
                    <button type="button" class="btn btn-primary float-right" style="margin-right: 10px; margin-top: 10px;">Novo universitario</button>
                <% end %>

                <%= link_to ranking_path, method: :get do %>
                    <button type="button" class="btn btn-primary float-right" style="margin-right: 10px; margin-top: 10px;">Ranking</button>
                <% end %>
                
            </div>
            <div class="col-xl-2" style="padding: 0;"></div>
        </div>
    </section>
</body>

</html>

app/views/students/new.html.erb
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<title>Login</title>
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link rel="stylesheet" type="text/css" href="/assets/bootstrap.min.css">
			<link rel="stylesheet" type="text/css" href="/assets/font-awesome.min.css">
			<link rel="stylesheet" type="text/css" href="/assets/icon-font.min.css">
			<link rel="stylesheet" type="text/css" href="/assets/animate.css">
			<link rel="stylesheet" type="text/css" href="/assets/hamburgers.min.css">
			<link rel="stylesheet" type="text/css" href="/assets/animsition.min.css">
			<link rel="stylesheet" type="text/css" href="/assets/select2.min.css">
			<link rel="stylesheet" type="text/css" href="/assets/util.css">
			<link rel="stylesheet" type="text/css" href="/assets/main.css">
		</head>
		<body>
			<div class="limiter">
				<div class="container-login100">
					<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">

						<%= form_for @student do |f| %>
							<span class="login100-form-title p-b-33">
								Novo Universitário
							</span>
		
							<div class="wrap-input100 validate-input">
						    	<%= f.text_field :name, autofocus: true, class: "input100", type: "text", placeholder: "Nome" %>
						    	<span class="focus-input100-1"></span>
								<span class="focus-input100-2"></span>
						  	</div>

						  	<div class="wrap-input100 validate-input">
						    	<%= f.text_field :age, autofocus: true, class: "input100", type: "text", placeholder: "Idade" %>
						    	<span class="focus-input100-1"></span>
								<span class="focus-input100-2"></span>
						  	</div>

						  	<div class="wrap-input100 validate-input">
						    	<%= f.text_field :gender, autofocus: true, class: "input100", type: "text", placeholder: "Sexo" %>
						    	<span class="focus-input100-1"></span>
								<span class="focus-input100-2"></span>
						  	</div>

						  	<div class="wrap-input100 validate-input">
						    	<%= f.text_field :bachelor_degree, autofocus: true, class: "input100", type: "text", placeholder: "Curso" %>
						    	<span class="focus-input100-1"></span>
								<span class="focus-input100-2"></span>
						  	</div>

						  	<div class="container-login100-form-btn m-t-20">
								<button class="login100-form-btn">
									Criar
									<%= f.submit "" %>
								</button>
							</div>
						<% end %>
					</div>
				</div>
			</div>

			<script src="/assets/jquery-3.2.1.min.js"></script>
			<script src="/assets/animsition.min.js"></script>
			<script src="/assets/bootstrap1.min.js"></script>
			<script src="/assets/select2.min.js"></script>
			<script src="/assets/moment1.min.js"></script>
			<script src="/assets/countdowntime.js"></script>
			<script src="/assets/main.js"></script>
	<!--		<%= javascript_include_tag "/assets/main" %> -->
		</body>
	</html>

app/views/students/play.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Game Sample</title>
</head>

<body>
<div>
	<%= link_to "Voltar", student_path(@student), id: "Voltar" %>
</div>
<div class="container">
    <!-- Phaser Game -->

    <div id="game-container" class="center">
    </div>
</div>

<!-- INCLUDES DAS LIBS -->

<script type="text/javascript" src="/javascripts/lib/phaser.js"></script>

<!-- INCLUDES DO JOGO -->


<script type="text/javascript" src="/javascripts/game.js.erb"></script>

</body>

<script type="text/javascript">
   var convert_points_path = "<%= convert_points_path %>";
</script>

</html>

app/views/students/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title> Calouro Simulator</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
        var jQuery_3_3_1 = $.noConflict(true);
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>

<body>
    <section>
        <div class="row" style="margin: 0">
            <div class="col-xl-12" style="min-height: 64px; background: #e9faff; padding: 0">
                <div class="row" style="margin: 0">     
                    <div class="col-lg-3"> <%= link_to 'voltar', root_path %> </div>
                    <div class="col-lg-6">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="text-center" style="border-top: none; color: #dc3545; font-weight: normal">Fome</th>
                                    <th class="text-center" style="border-top: none; color: #28a745; font-weight: normal">Saúde</th>
                                    <th class="text-center" style="border-top: none; color: #28a745; font-weight: normal">Higiene</th>
                                    <th class="text-center" style="border-top: none; color: #ffc107; font-weight: normal">Energia</th>
                                    <th class="text-center" style="border-top: none; color: #6c757d; font-weight: normal">Felicidade</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar bg-danger" id="hunger" style="width:<%= @student.hunger %>%"></div>
                                        </div>                          
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar bg-danger" id="health" style="width:<%= @student.health %>%"></div>
                                        </div>                          
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar bg-success" id="hygiene" style="width:<%= @student.hygiene %>%">
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar bg-warning" id="energy" style="width:<%= @student.energy %>%"></div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="progress">
                                            <div class="progress-bar bg-secondary" id="mood" style="width:<%= @student.mood %>%"></div>
                                        </div>
                                    </td>
                                    <label id="coeficiente"> Coeficiente: <%= @student.coefficient %> </label>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-3">
                        <a href="#" data-toggle="modal" data-target="#logoutModal">
                             <%= image_tag "user.jpg", :style => "margin-top:21px", width:"64", height:"64", title:"Logout", class:"rounded-circle float-right"%>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="row" id="emoji" style="margin: 0">
            <div class="col-xl-12 text-center" style="padding: 0; height: 256px;">
                <div id="emojiGenerico", class="<%= @student.icon %>"></div>
            </div>
        </div>
    </section>
    <footer>
        <div class="row" style="margin: 0">
            <div class="col-xl-12" style="min-height: 106px; background: #e9faff; padding: 0">
                <div class="row" style="margin: 0">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-6" style="margin-top: 10px">
                        <table class="table" style="margin: 0">
                            <tr>
                                <td style="border-top: none">
                                    <div id="feed_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Fome"> 
                                      <%= image_tag "fome.png", id: "feed_link", width:"48", class:"guedesbixa" %>
                                    </div>
                                </td>
                                <td style="border-top: none">
                                    <div id="bath_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Higiene">
                                      <%= image_tag "higiene.png", id: "bath_link", width:"48", class:"guedesbixa" %>
                                    </div>
                                </td>
                                <td style="border-top: none">
                                    <div id="health_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Remédio">
                                      <%= image_tag "health.png", id: "cure_link", width:"48", class:"guedesbixa" %>
                                    </div>
                                </td>
                                <td style="border-top: none">
                                    <div id="exercise_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Atividade"> 
                                      <%= image_tag "atividade.png", id: "exercise_link", width:"48", class:"guedesbixa" %>
                                    </div>
                                </td>
                                <td style="border-top: none">
                                    <%= link_to play_path, :method => :get do %>
                                        <div id="play_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Jogar"> 
                                        <%= image_tag "play.png", id: "play_link", width:"48", class:"guedesbixa" %>
                                        </div>
                                    <% end %>
                                </td>
                                <td style="border-top: none">
                                    <div id="study_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Estudar"> 
                                        <%= image_tag "study.png", id: "study_link", width:"48", class:"guedesbixa" %>
                                        </div>
                                </td>
                                <td style="border-top: none">
                                    <div id="sleep_btn" class="btn" style="background: #e9faff"  data-toggle="tooltip" title="Dormir"> 
                                      <%= image_tag "sleep.png", id: "sleep_link", width:"48", class:"guedesbixa" %>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>

<script>

    $(document).ready(function(){
        
        $('[data-toggle="tooltip"]').tooltip();
        
        var altura = $(window).height();
        
        $('#emoji').css({
            'margin-top': ((altura-468)/2)+'px',
            'margin-bottom': ((altura-468)/2)+'px',
        });

        $('#feed_link').click(function () {
           $.ajax({
            type: "GET",
            url: "<%= feed_path %>",
            dataType: "json",
            success: function(student){
                $('#hunger').css({
                    'width': student.hunger.toString() + '%'
                });
                $('#mood').css({
                    'width': student.mood.toString() + '%'
                });
            }
           });
        });

        $('#cure_link').click(function () {
           $.ajax({
            type: "GET",
            url: "<%= cure_path %>",
            dataType: "json",
            success: function(student){
                $('#health').css({
                    'width': student.health.toString() + '%'
                });
                $('#mood').css({
                    'width': student.mood.toString() + '%'
                });
            }
           });
        });

        $('#bath_link').click(function () {
           $.ajax({
            type: "GET",
            url: "<%= bath_path %>",
            dataType: "json",
            success: function(student){
                $('#hygiene').css({
                    'width': student.hygiene.toString() + '%'
                });
                $('#mood').css({
                    'width': student.mood.toString() + '%'
                });
            }
           });
        });

        $('#exercise_link').click(function () {
           $.ajax({
            type: "GET",
            url: "<%= exercise_path %>",
            dataType: "json",
            success: function(student){
                $('#energy').css({
                    'width': student.energy.toString() + '%'
                });
                $('#mood').css({
                    'width': student.mood.toString() + '%'
                });
            }
           });
        });

        $('#sleep_link').click(function () {
           $.ajax({
            type: "GET",
            url: "<%= sleep_path %>",
            dataType: "json",
            success: function(student){
                $('#energy').css({
                    'width': student.energy.toString() + '%'
                });
                $('#mood').css({
                    'width': student.mood.toString() + '%'
                });
            }
           });
        });

        $('#study_link').click(function () {
           $.ajax({
            type: "GET",
            url: "<%= study_path %>",
            dataType: "json",
            success: function(student){
                document.getElementById('coeficiente').innerHTML = 'Coeficiente: <%= @student.coefficient %>';

                $('#energy').css({
                    'width': student.energy.toString() + '%'
                });
                $('#hygiene').css({
                    'width': student.hygiene.toString() + '%'
                });
                $('#health').css({
                    'width': student.health.toString() + '%'
                });
                $('#mood').css({
                    'width': student.mood.toString() + '%'
                });
            }
           });
        });

        function update() {
            $.ajax({
                type: "GET",
                url: "<%= update_path %>" ,
                dataType: "json",
                success: function(student) {
                    console.log('hunger: ', student.hunger.toString(),'   hygiene: ', student.hygiene.toString(),'   energy: ', student.energy.toString(),'   mood: ', student.mood.toString());
                    $('#emojiGenerico').removeClass();
                    $('#emojiGenerico').addClass(student.icon.toString());
                    $('#hunger').css({
                        'width': student.hunger.toString() + '%'
                    });
                    $('#health').css({
                        'width': student.health.toString() + '%'
                    });
                    $('#hygiene').css({
                        'width': student.hygiene.toString() + '%'
                    });
                    $('#energy').css({
                        'width': student.energy.toString() + '%'
                    });
                    $('#mood').css({
                        'width': student.mood.toString() + '%'
                    });
                }
            });
        };

        setInterval(update, 5000);

    });

</script>

<!-- Small modal -->
<div class="modal" id="logoutModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Log Out <i class="fa fa-lock"></i></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                <p><i class="fa fa-question-circle"></i> Are you sure you want to log-off? <br /></p>
                <div class="actionsBtns">
                    <form action="/logout" method="post">
                        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                        <input type="submit" class="btn btn-default bgn-secondary" data-dismiss="modal" value="Logout" />
                        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>